-- --------------------------------------------------------
-- Hôte:                         127.0.0.1
-- Version du serveur:           8.0.30 - MySQL Community Server - GPL
-- SE du serveur:                Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Listage de la structure de la base pour cuisine
CREATE DATABASE IF NOT EXISTS `cuisine` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `cuisine`;

-- Listage de la structure de table cuisine. commentaires
CREATE TABLE IF NOT EXISTS `commentaires` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_recet_com` int DEFAULT NULL,
  `pseudo` varchar(255) DEFAULT NULL,
  `commentaire` text,
  `date_creation_com` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=latin1;

-- Listage des données de la table cuisine.commentaires : ~39 rows (environ)
DELETE FROM `commentaires`;
INSERT INTO `commentaires` (`id`, `id_recet_com`, `pseudo`, `commentaire`, `date_creation_com`) VALUES
	(1, 1, 'Najma', 'Mmmmm c\'était très bon.', '2018-06-21 03:25:00'),
	(2, 1, 'Mounia', 'Demain je la fais.', '2018-06-21 04:42:43'),
	(3, 1, 'Akab', 'Bougez pas les filles je ramène le poisson', '2018-06-21 04:50:03'),
	(4, 1, 'Christine', 'Oh un marin est parmi nous.', '2018-06-21 04:52:42'),
	(5, 2, 'Domino', 'Un vrai délice, même les enfants ont aimés.', '2018-06-25 03:28:06'),
	(6, 2, 'Mikado', 'Toujours de bonnes surprises à déguster.', '2018-06-25 03:41:10'),
	(7, 3, 'Gupta', 'Ca me rappelle quand j\'étais petit.', '2018-06-26 02:14:45'),
	(8, 3, 'Fetoma', 'Alors retours aux sources ?', '2018-07-02 04:38:43'),
	(9, 4, 'El Chicano', 'Mama mia cette recette va mettre le fuego dans la culotte.', '2018-07-20 08:05:08'),
	(10, 4, 'Paquita', 'Ola ombre El Chicano tu es mucho caliente.', '2018-07-23 02:56:23'),
	(11, 5, 'Freakyman', 'Y en a marre.', '2018-07-23 08:37:34'),
	(12, 5, 'Ganesh', 'Namasté,\r\nQue de souvenir', '2018-07-24 04:06:30'),
	(13, 5, 'Paquita', 'les enfants vont adorer.', '2018-07-24 05:23:59'),
	(14, 6, 'Freakyman', 'Des boulettes, des boulettes, qui veut des boulettes.', '2018-07-27 03:44:46'),
	(15, 6, 'Killer', 'Je crois que t\'es mort là.', '2018-07-27 04:32:08'),
	(16, 5, 'Paquita', '@Freakyman viens je vais te calmer.', '2018-07-27 04:33:44'),
	(17, 2, 'Paquita', 'Moi je rajoute du piment vert frais coupé en rondelles.\r\nMon Doudou adore quand c\'est hot.', '2018-07-27 04:39:43'),
	(18, 6, 'Pizzaïolo', 'Je crois que c\'est bien enfourné là.', '2018-07-27 12:12:55'),
	(19, 6, 'Nunuche', 'Oh ! Mais y a que des guerriers ici.', '2018-07-27 12:20:41'),
	(20, 6, 'Cruella', 'T\'inquiètes Nunuche on va te les mater.', '2018-07-27 12:23:35'),
	(22, 7, 'Christine', 'Quand mon Meouw en fait, elles sont fines et croustillantes; comme j\'aime.\r\nMmmmmmmmmmmm !', '2018-07-31 05:32:43'),
	(23, 9, 'Freakyman', 'C\'est bon pour le boubergol.', '2018-08-04 14:59:16'),
	(24, 9, 'Freakyman', 'Ou le boubinol.', '2018-08-04 15:02:13'),
	(25, 10, 'Paquita', 'Je l\'ai faite et toutes mes amies m\'ont demandé la recette.', '2018-08-06 07:35:47'),
	(26, 13, 'Lourdita', 'Moi qui aime le sucré salé, je cours m\'acheter du poisson pour faire cette recette.', '2018-08-15 06:53:53'),
	(27, 13, 'La Gorda', 'Mmmm miam.', '2018-08-15 07:03:17'),
	(28, 13, 'Christine', 'Mon meouw est tout gentil en ce moment.', '2018-08-15 08:06:52'),
	(29, 22, 'Bijou', 'Mon chéri m\'en a fait ce weekend, un délice.', '2019-05-06 08:19:30'),
	(30, 25, 'Line Conu', 'Elle donne envie cette idée de coings, demain je la fais.', '2019-10-17 15:23:51'),
	(31, 27, 'Chris La mère Guez', 'Mmmm, ça à l\'air tellement bon que je vais la tester de suite.', '2020-01-10 17:19:47'),
	(32, 4, 'Gloutonne', 'Trop fort tu m\'as fait aimer les poivrons.', '2020-02-22 11:32:00'),
	(33, 14, 'Hitomi', 'C\'est presque comme là-bas.', '2020-05-31 14:22:17'),
	(34, NULL, 'Lara Leuze', 'Et les piments verts ou rouges? On les met quand? On doit les couper ou les laisser entiers? ', '2021-03-13 10:31:53'),
	(35, NULL, 'Lara Leuze', 'Et les piments verts ou rouges? On les met quand? On doit les couper ou les laisser entiers? ', '2021-03-13 10:32:32'),
	(36, NULL, 'El Freaky', 'Pour moi c\'est ma madeleine. Sniff.', '2023-01-17 10:27:47'),
	(37, NULL, 'El Freaky', 'Pour moi c\'est ma madeleine. Sniff.', '2023-01-17 10:28:22'),
	(38, NULL, 'Pseudo', 'Un commentaire test.', '2023-01-17 11:00:18'),
	(39, NULL, 'fqdfgs', 'sdfgsdfg', '2023-01-17 11:05:17'),
	(40, NULL, 'sdfsd', 'sfsd', '2023-01-17 11:07:02');

-- Listage de la structure de table cuisine. img_cuisine
CREATE TABLE IF NOT EXISTS `img_cuisine` (
  `id_img` smallint unsigned NOT NULL AUTO_INCREMENT,
  `recette_id` smallint unsigned NOT NULL,
  `img_descrip` text NOT NULL,
  `name_img` varchar(100) NOT NULL,
  `text_alt` varchar(100) DEFAULT NULL,
  `img_date` timestamp NOT NULL,
  PRIMARY KEY (`id_img`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

-- Listage des données de la table cuisine.img_cuisine : 0 rows
DELETE FROM `img_cuisine`;
/*!40000 ALTER TABLE `img_cuisine` DISABLE KEYS */;
/*!40000 ALTER TABLE `img_cuisine` ENABLE KEYS */;

-- Listage de la structure de table cuisine. membres
CREATE TABLE IF NOT EXISTS `membres` (
  `id` int NOT NULL AUTO_INCREMENT,
  `pseudo` varchar(255) NOT NULL,
  `mail` varchar(255) NOT NULL,
  `mdp` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- Listage des données de la table cuisine.membres : ~4 rows (environ)
DELETE FROM `membres`;
INSERT INTO `membres` (`id`, `pseudo`, `mail`, `mdp`) VALUES
	(1, 'Paquita', 'paquita@free.fr', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'),
	(2, 'Freakyman', 'freakyman@laouf.mr', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'),
	(3, 'Lourdita', 'lourdita@free.fr', '0d467c11c1f788a43266782aac388b66b0f22551'),
	(4, 'lamotte', 'mailt@mere.fr', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220');

-- Listage de la structure de table cuisine. origines
CREATE TABLE IF NOT EXISTS `origines` (
  `id_origine` int NOT NULL DEFAULT '0',
  `origine_id` int NOT NULL,
  `origine` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id_origine`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Listage des données de la table cuisine.origines : ~13 rows (environ)
DELETE FROM `origines`;
INSERT INTO `origines` (`id_origine`, `origine_id`, `origine`) VALUES
	(0, 0, ''),
	(1, 1, 'Espagne'),
	(2, 2, 'France'),
	(3, 3, 'Indes'),
	(4, 4, 'Maroc'),
	(6, 52, 'Viêt-Nam'),
	(7, 53, 'Thaïlande'),
	(8, 21, 'Alsace'),
	(9, 5, 'Asie'),
	(10, 51, 'Japon'),
	(11, 54, 'Chine'),
	(12, 12, 'Méditerranée'),
	(13, 6, 'Italie');

-- Listage de la structure de table cuisine. recettes
CREATE TABLE IF NOT EXISTS `recettes` (
  `id_recette` int NOT NULL AUTO_INCREMENT,
  `date_creation` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `plat` varchar(255) DEFAULT NULL,
  `recette` varchar(255) DEFAULT NULL,
  `mots_cles` varchar(255) NOT NULL,
  `origine_id` varchar(255) DEFAULT NULL,
  `regOrigId` int NOT NULL,
  `presentation` text,
  `nbr_pers` int DEFAULT NULL,
  `difficulte` varchar(20) NOT NULL,
  `ingrediens` text,
  `epices` text,
  `tps_prep` time DEFAULT NULL,
  `tps_cuis` time DEFAULT NULL,
  `preparation` text,
  `cuisson` text,
  `suggestion` text,
  `nom_img_min` varchar(255) NOT NULL,
  `nom_img` varchar(255) NOT NULL,
  `alt_img` varchar(255) NOT NULL,
  `nom_img_grd` varchar(255) NOT NULL,
  PRIMARY KEY (`id_recette`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=latin1;

-- Listage des données de la table cuisine.recettes : ~47 rows (environ)
DELETE FROM `recettes`;
INSERT INTO `recettes` (`id_recette`, `date_creation`, `plat`, `recette`, `mots_cles`, `origine_id`, `regOrigId`, `presentation`, `nbr_pers`, `difficulte`, `ingrediens`, `epices`, `tps_prep`, `tps_cuis`, `preparation`, `cuisson`, `suggestion`, `nom_img_min`, `nom_img`, `alt_img`, `nom_img_grd`) VALUES
	(1, '2018-06-21 12:08:52', '1', 'Tajine de congre.', 'poisson, maroc', '4', 4, 'Une recette qui se fait du nord au sud du Maroc.\r\nIl s\'y mêle les senteurs de la cannelle et du safran pour relever la chair d\'un poisson rare sur nos étals de poissonnier.', 4, 'facile', 'congre,\r\noignons,\r\nraisins secs blonds.', 'safran,\r\ncannelle en poudre,\r\n1 bâton de cannelle.\r\nSel et poivre.', '00:15:00', '01:00:00', 'Faire tremper le safran et les raisins secs.\r\nÉmincez les oignons.\r\n', 'Faire revenir les oignons dans une cocotte,\r\nmettre les morceaux de congre dessus,\r\najouter les raisins trempés, les épices,\r\ncouvrir à hauteur d\'eau et laisser mijoter une heure.', 'Préférer les morceaux près de la tête, \r\nils n\'ont pas de petites arêtes comme ceux de la queue.\r\nServir avec des salades marocaines.\r\n', 'taj_congre_oign_min.jpg', 'taj_congre_oign.jpg', 'tajine congre pomme de terre', 'taj_congre_oign_grd.jpg'),
	(2, '2018-06-23 01:42:08', '2', 'Salade de tomates aux noix de cajou.', 'Noix de cajou, salades, indes', '3', 3, 'Une surprenante association entre la noix de cajou et la tomate.', 4, 'facile', 'Tomates,\r\noignons,\r\nnoix de cajou.', 'Garam masala,\r\nhuile.', '00:15:00', '00:00:00', 'Mettre les tomates coupées en petits dés dans un saladier.\nDisposez dessus quelques rondelles fines d\'oignons.\nParsemez avec les noix de cajou grillées.\nAjoutez un filet d\'huile.\nSaupoudrez de garam masala.\n', 'Sans.', 'Ceux qui aiment manger relevé, rajoutez du piment vert frais coupé en rondelles.', 'salade_de_tomates_aux_noix_cajou_min.jpg', 'salade_de_tomates_aux_noix_cajou.jpg', 'Salade de tomates aux noix cajou.', 'salade_de_tomates_aux_noix_cajou_grd.jpg'),
	(3, '2018-07-02 11:35:26', '3', 'Pommes de terre à l\'ail.', 'Pommes de terre, patate, patates, maroc', '4', 4, 'Une recette délicieuse et facile à préparer.', 4, 'facile', 'Pommes de terre,\r\noignons,\r\nail,\r\nCoriandre fraîche.', 'Curcuma,\r\ngingembre,\r\ncoriandre en poudre,\r\nsel,\r\npoivre.', '00:15:00', '00:30:00', 'Emincez les oignons,\r\ncoupez les Pdt en cubes moyens,\r\néqueutez la coriandre.', 'Faire fondre les oignons,\r\nrajoutez les épices et l\'ail écrasé,\r\nfaire revenir 5mn,\r\nmettre les Pdt et mouillez pas tout à fait à hauteur d\'eau.\r\nLaisser mijoter 25mn.', 'Vous pouvez remplacer les Pdt par des carottes.\r\nEt rajouter quelques olives noires dénoyautées.', 'pommes_de_terre_ail_min.jpg', 'pommes_de_terre_ail.jpg', 'pommes de terre à l\'ail', 'pommes_de_terre_ail_grd.jpg'),
	(4, '2018-07-20 09:20:08', '3', 'Tajine tomates, poivrons et piments.', 'Tomate, poivrons, piments, corne de bœuf, maroc', '4', 4, 'Un plat simple', 4, 'facile', '4 tomates,\r\n4 poivrons corne de boeuf,\r\n4 piments (facultatif),\r\n4 gousses d\'ail.', 'piment rouge en poudre,\r\ncumin en poudre', '00:15:00', '00:30:00', 'Peler les tomates et les poivrons si ce n\'est pas des cornes de bœuf.\r\nLes ouvrir et les épépiner.\r\nLes couper en lanières.\r\n', 'Faire chauffer de l\'huile d\'olive avec la poudre de piment.\r\nY faire revenir l\'ail sans le brûler.\r\nRajouter les tomates et les poivrons.\r\nSalez poivrez et faire cuire 10mn à feux doux.\r\nDécouvrir et faire réduire le jus 15 mn.\r\nPour finir saupoudrez de cumin,\r\n couvrir 2/3 minutes.\r\nPuis servir.', 'Attention au piment.\r\nPrenez en des doux pour commencer.\r\nEt si vous voulez des forts enlevez quand même les graines.\r\nLes cornes de bœuf ont la peau plus fine, c\'est pour cela qu\'il est inutile de les peler.', 'tajine_tomates_poivrons_min.jpg', 'tajine_tomates_poivrons.jpg', 'tajine_tomates_poivrons', 'tajine_tomates_poivrons_grd.jpg'),
	(5, '2018-07-22 01:19:11', '7', 'Chutney de bananes.', 'Bananes, gingembre, citron vert, raisins sec, indes, tamarin, chutney', '3', 3, 'Voilà un surprenant mariage entre la banane et le tamarin.', 4, 'facile', '1 banane et  1/2 par pers,\r\nRaisins secs,\r\n1 morceaux de gingembre frais,\r\n1/2 citron vert (facultatif).', 'Pulpe de tamarin,\r\n1 càs de sucre,\r\nPiment en poudre,\r\nCumin.', '00:15:00', '00:00:00', 'Préparez le tamarin si vous l\'avez acheté avec des noyaux, la pulpe doit être légèrement liquéfié. Sinon il en existe de la toute prête.\r\nHachez très fin le gingembre frais.\r\nFaites griller à sec le cumin et le piment.\r\nPressez le citron vert pour en exprimer le jus (facultatif).\r\nÉpluchez et coupez les bananes en rondelles moyennes.\r\nVersez tout cela dans un saladier.\r\nBien mélanger et servir frais.', 'Sans', 'Attention quand vous grillez le piment en poudre, \r\naérez bien la pièce ça peut vous irriter les bronches.\r\nVous pouvez faire gonfler les raisins secs 1 heure avant dans de l\'eau chaude, pour les rendre plus moelleux.', 'chutney_banane_min.jpg', 'chutney_banane.jpg', 'chutney de banane', 'chutney_banane_grd.jpg'),
	(6, '2018-07-26 06:33:47', '3', 'Tajine de petits pois et oeufs.', 'Petits pois, oeufs, maroc', '4', 4, 'Une recette facile à préparer et délicieuse à manger.', 4, 'facile', '500grs de petits pois,\r\nun oignon,\r\n1 cas de concentré de tomate,\r\n2 gousses d\'ail,\r\n1 cas de persil haché,\r\n2 càs d\'huile (d\'olive),\r\n4 oeufs.', 'Sel,\r\npoivre,\r\ncumin.', '00:15:00', '00:20:00', 'Hacher finement les oignons et le persil.\r\n', 'Faire revenir les oignons dans un peu d\'huile.\r\nRajouter le concentré de tomate dilué dans un peu d\'eau, \r\nmettre les petits pois, le sel, le poivre, le cumin et le persil haché.\r\nFaire mijoter 10mn à couvert.\r\nRépartissez les oeufs sur les petits pois.\r\nLaissez cuire jusqu\'à ce que le blanc des oeufs soit dur, \r\nmais pas les jaunes.', 'Pour un repas plus riche, vous pouvez rajouter des boulettes de viande hachée.', 'tajine-petits-pois-aux-oeufs_min.jpg', 'tajine-petits-pois-aux-oeufs.jpg', 'tajine-petits-pois-aux-oeufs', ''),
	(7, '2018-07-30 06:17:23', '3', 'Galettes de pommes de terre (Grumbeerekiechle).', 'Pommes de terre, Alsace', '21', 21, 'De savoureuses galettes croustillantes à l\'extérieur et fondantes à l\'intérieur.', 4, 'facile', '1 kg de pommes de terre,\r\n2 oeufs,\r\n1 oignon,\r\ndu persil haché.', 'Sel,\r\npoivre,\r\nnoix de muscade\r\nde l\'huile.', '00:20:00', '00:30:00', 'Pelez et râpez (pas trop fin) les pommes de terre dans un grand saladier.\r\nEssorez les, puis jetez le jus mais pas l\'amidon qui s\'est déposé au fond.\r\nRajoutez les oeufs, les oignons coupés tous fins, le persil haché et les épices.\r\nBien mélanger le tout.', 'Sur une poêle mettre une cuillère à soupe bien pleine de préparation,\r\nbien aplatir pour avoir une épaisseur d\'environ 7mm.\r\nLaisser cuire sans brûler,\r\nretourner et faites cuire l\'autre face.', 'Se déguste chaud avec une bonne salade de pissenlits quand c\'est la saison.', 'galettes_de_pommes_de_terre_min.jpg', 'galettes_de_pommes_de_terre.jpg', 'galettes de pommes de terre', ''),
	(8, '2018-07-30 07:17:23', '4', 'Pieds de veau aux pois chiches (Hargma ou kr3in).', 'Pieds de veau, Hargma, kr3in, abats blancs, pois chiches, maroc', '4', 4, 'Initialement c\'était un plat sépharade puis les marocains l\'ont adopté et adapté à leur goût.', 4, 'facile', '1 Pied de veau nettoyé, gratté et coupé par vôtre boucher\r\n1 Oignon émincé\r\n4 Gousses d\'ail\r\n1 Bol de pois chiches avec la peau déjà trempé\r\n1 Bol de raisins secs', 'Paprika,\r\ncannelle en bâton,\r\ngingembre en poudre,\r\ncoriandre en poudre,\r\nquelques pistils de safran,\r\npiment en poudre,\r\n½ càc de curcuma,\r\n3 Càs d\'huile d\'olive,\r\nsel,\r\npoivre.', '00:10:00', '01:30:00', 'Mettez les pois chiches à tremper la veille.\r\nLe jour même mettez les raisins à tremper dans de l\'eau chaude.\r\nRéduisez le safran en poudre à l\'aide d\'un mortier et mettez le dans un verre d\'eau chaude.\r\nRincer les pieds de veau.\r\nÉmincer les oignons.\r\nÉcraser les gousses d\'ail.', 'Mettez tout dans un autocuiseur sauf les raisins secs.\nRajoutez 1 litre d\'eau. Fermez et laissez cuire pendant 1 heure.\nOuvrez l\'autocuiseur, rajoutez les raisins secs de l\'eau si besoin,\npas trop sinon il faudra faire réduire pour avoir une sauce onctueuse.\nFinissez la cuisson jusqu\'à ce que la chair des pieds de veau soit fondante.', 'A manger chaud avec du bon pain,\r\nmais je préfère la déguster avec un bon riz basmati.\r\nVous pouvez aussi faire cette recette avec des pieds de mouton.', 'pieds_de_veau_aux_pois_chiches_min.jpg', 'pieds_de_veau_aux_pois_chiches.jpg', 'Pieds de veau aux pois chiches.', ''),
	(9, '2018-08-04 08:06:48', '1', 'Maquereaux grillés au gingembre et sauce soja.', 'poisson, grillade, grillades, Japon', '5', 51, 'Pour changer des sempiternelles sardines grillées.', 4, '', '4 maquereaux moyen.', 'gingembre frais,\r\nsauce soja,\r\nsucre,\r\nvinaigre de riz japonais.', '00:15:00', '00:12:00', 'Videz, nettoyez et coupez la tête des maquereaux.\nFaites trois incision de chaque côté pour faire pénétrer la marinade.\nMettre à mariner dans un plat non métallique avec le mélange de gingembre, \nde sauce soja, sucre et vinaigre de riz japonais.\nLe temps de marinade peut être de 1/4 d\'heure si vous êtes pressé, \nmais ce sera meilleur si vous le faite la veille.', 'Faire griller au grill ou au barbecue  6 minutes par face.', 'N\'oubliez pas que le poisson trop cuit devient sec; et c\'est pas bon.\r\nA vous d\'ajuster le temps pour ne pas le gâcher.\r\nVous pouvez les accompagner avec une salade de choux à la japonaise. ', 'maquereau_min.jpg', 'maquereau.jpg', 'maquereau', ''),
	(10, '2018-08-05 05:40:46', '4', 'Poulet au miel, safran et pignons', 'Poulet, France, miel, safran, pignons', '2', 2, 'Une recette sucrée salée pour un déjeuner festif.', 4, '', '1 poulet\r\n1 oignon\r\n50cl de bouillon de volaille\r\n3 càs de pignons de pin\r\n2 càs de miel\r\n3 càs de raisins secs', '1 dizaine de filaments de safran\r\n6 grains de poivre de la Jamaïque\r\n1 feuille de laurier\r\nHuile\r\nCurcuma en poudre\r\nGingembre en poudre\r\nCoriandre en poudre\r\nSel\r\nPoivre', '00:20:00', '00:45:00', 'Coupez le poulet.\r\nÉmincez l\'oignon.\r\nPréparez le bouillon de volaille.\r\nMettez les filaments de safran dans un bol avec de l\'eau chaude.', 'Faites dorer les morceaux de poulet dans une cocotte, réservez.\r\nJetez le gras du fond de la cocotte, puis faite fondre l\'oignon.\r\nRemettez le poulet dans la cocotte avec, le bouillon, le laurier, les raisins secs et toutes les épices.\r\nCouvrez et faites mijoter 45 min.\r\nDélayez le miel dans la sauce et faites la réduire jusqu\'à ce qu\'elle soit onctueuse.\r\nFaites griller les pignons à sec et parsemez les assiettes au moment de servir.', 'Pour avoir un maximum d\'arôme du safran faites le tremper la veille. \r\nPour le choix du miel à vous de voir lequel vous avez ou que vous aimez. Pour une recette plus diététique enlevez la peau du poulet.', 'poulet_miel_safran_pignons_min.jpg', 'poulet_miel_safran_pignons.jpg', 'poulet miel safran pignons', ''),
	(11, '2018-08-09 05:11:24', '2', 'Salade de poulpe à la roquette.', 'Poulpe, salades, france, méditterranée', '2', 2, 'Ah ! Le poulpe. Voilà une bonne idée pour se régaler en été.', 4, '', '1 poulpe cuit,\r\nde la roquette,\r\n1 citron,\r\nde l\'ail.', 'Du paprika doux,\r\ndu paprika fort,\r\nde la fleur sel,\r\ndu poivre blanc,\r\nde l\'huile d\'olive.', '00:30:00', '00:00:00', 'Enlevez la peau du poulpe puis coupez le en rondelles.\r\nDans un mélange de citron, d\'ail,de paprika doux et d\'huile d\'olive, mettez le à mariner au frais environ 6 heures (plus c\'est mieux).\r\nPuis disposez un lit de roquette sur une assiette et mettez le poulpe par dessus, assaisonnez avec la fleur de sel, le poivre blanc et le paprika fort.\r\nRajoutez un filet de jus de citron et dégustez.', '', '', 'poulpe_sous_vide_min.jpg', 'poulpe_sous_vide.jpg', 'poulpe_sous_vide', 'poulpe_sous_vide_grd.jpg'),
	(12, '2018-08-09 12:40:20', '1', 'Daurade à la chinoise.', 'poisson, Chine', '5', 54, 'Une recette facile que nous adorons faire depuis des années.', 2, '', '1 belle daurade,\r\n1 càs de piment rouge,\r\n2 càs d\'échalote,\r\n2 càs de gingembre,\r\n2 càs d\'ail.', '3 càs d\'huile d\'arachide,\r\n3 càs de sauce soja,\r\n2 càs de vin chinois.', '00:20:00', '00:25:00', 'Videz et nettoyez la daurade.\r\nEpongez l\'eau avec du papier absorbant.\r\nFaites trois entailles de chaque côté.\r\nHachez le piment, l\'échalote, le gingembre et l\'ail. ', 'Faites revenir l\'ail et le gingembre dans l\'huile, sans brûler l\'ail.\r\nRajouter la daurade et faire brunir sur les deux faces.\r\nPuis rajoutez le piment, la sauce soja, le vin, le sucre et un petit verre d\'eau.\r\nLaissez cuire à feu moyen à découvert.\r\nEnsuite vous rajoutez l\'échalote, vous couvrez et laissez cuire à feu doux 3 min.\r\nSe déguste avec du riz nature.', 'Pour le vin chinois vous pouvez le remplacer par du vinaigre de Xérès.', 'daurade_a_la_chinoise_min.jpg', 'daurade_a_la_chinoise.jpg', 'daurade', ''),
	(13, '2018-08-09 14:57:57', '1', 'Poisson au caramel ou (cá kho tô)', 'poisson, Viêt-Nam, Viet-Nam', '5', 52, 'On ne présente pas ce plat, il est servi dans tout le Viêt-Nam.', 4, '', '1 poison de 1 kilo ou 4 belles darnes,\r\n1 échalote hachées,\r\n3 gousses d’ail,\r\n2 càs de nuoc mam,\r\n2 piments rouge frais.', '2 càs d’huile,\r\n2 càs de sucre,\r\nsel,\r\npoivre.', '00:00:00', '00:00:00', 'Videz et lavez vôtre poisson, coupez le en 4. (Si vous n\'avez pas choisi les darnes).\r\nEpongez le.\r\nFaites marinez le poisson dans un mélange d\'ail haché, d\'échalote et 2 càs de nuoc mam pendant 20 min.\r\nDans une casserole mettre le sucre avec une goute d\'eau pour faire le caramel.\r\nAttention à ne pas le brûler sinon il devient amère.\r\nPuis ajouter de l\'eau pour faire la sauce. ', 'Dans une cocotte mettre le poisson avec sa marinade,\r\najouter le piment, de l\'eau et la sauce caramel.\r\nLe liquide doit couvrir le poisson.\r\nFaire mijoter à feux moyen environ 1 heure.\r\nPuis saupoudrez de poivre.\r\nServir avec du riz parfumé.', '', 'poisson_caramel_min.jpg', 'poisson_caramel.jpg', 'poisson_caramel', ''),
	(14, '2018-08-16 13:23:26', '1', 'Riz à sushi', 'riz, Japon', '5', 51, 'Le riz est l\'ingrédient principal des sushis alors on prend des notes pour améliorer la chose.', 2, 'difficile', '200 grs de riz rond à sushi, \r\n6 càs vinaigre de riz,\r\n2 càs de sucre blanc en poudre', '1 càc de sel, ', '00:10:00', '00:15:00', 'Laver 3 fois le riz jusqu\'à ce que l\'eau devienne claire et faire égoutter dans une passoire.\r\nMettre le vinaigre de riz dans un bol avec le sucre et le sel mélangez le tout jusqu\'à dissolution. ', 'Mettre à cuire le riz égoutté dans un rice cooker (si vous en avez un) avec 1 fois et demi son volume d\'eau.\r\nQuand çà s\'arrête laisser reposer 5 min. Puis verser le riz dans un récipient large et non métallique,\r\nensuite arrosez le de la préparation de vinaigre de riz et mélangez délicatement avec une cuillère en bois,\r\nsi vous êtes doué vous pouvez éventer en même temps pour refroidir le riz.', '', 'riz_sushi_min.jpg', 'riz_sushi.jpg', 'Photo de riz.', ''),
	(15, '2018-08-25 08:35:59', '0', 'Caliente', 'pois chiches, féculent, maroc, méditterranée ', '4', 4, 'C\'est une préparation à base de farine de pois chiches que l\'on cuit de différentes façons, dans plusieurs pays du pourtour méditerranéen.', 0, 'facile', '250 grs de farine de pois chiches non grillée,\r\n1 litre d\'eau,\r\n3 càs d\'huile d\'olive.', 'Sel,\r\npoivre ou cumin.', '00:15:00', '01:00:00', 'Dans une terrine mélanger la farine de pois chiches avec l\'eau, l\'huile d\'olive et le sel.\r\nVous devez obtenir une pâte fluide et sans grumeaux.\r\nLaisser reposer au moins 6 heures. Certains préconisent 24 heures.\r\nPenser à remuer le mélange de temps en temps.', 'Huilez un plat à four à bord haut.\r\nRemuez une dernière fois avant de verser le mélange dans le plat.\r\nFaire cuire entre 45 min et 1 heure à 210 degrés.\r\nLe dessus doit être un peu gratiné et si les bords sont bien dorés c\'est parfait.\r\n', 'Servir chaud ou tiède saupoudré de poivre ou de cumin.\r\nCertains mettent de la harissa dessus.', 'caliente_min.jpg', 'caliente.jpg', '', ''),
	(16, '2018-09-01 08:08:01', '4', 'Tajine d\'agneau aux pruneaux.', 'pruneaux, maroc', '4', 4, 'Le tajine aux pruneaux est un plat de fête très riche.', 4, '', '1 kgs d\'épaule ou collier d\'agneau,\r\n300 grs de pruneaux,\r\n200 grs d\'amandes,\r\n2 œufs,\r\n1 gros oignon.', 'Cannelle en bâton,\r\nCannelle en poudre,\r\n1 pincée de gingembre,\r\nsafran,\r\n1 càs graines de sésame\r\nhuile,\r\nsel,\r\npoivre.', '00:10:00', '01:00:00', 'Hacher l\'oignon en petit dés.\r\nFaire gonfler les pruneaux dans une casserole avec de l\'eau et un peu de cannelle en poudre.\r\nFaire cuire les œufs à la coque.\r\nÉmonder les amandes et les faire griller dans un peu d\'huile.', 'Faire revenir les morceaux de viandes dans un peu d\'huile puis réservez.\r\nFaire fondre l\'oignon coupé en petit dés.\r\nRemettre la viande ajouter toutes les épices.\r\nCouvrir à hauteur d\'eau et laisser mijoter à feux doux entre 45min et 1 heure.\r\n10min avant la fin de la cuisson rajouter les pruneaux et finissez la cuisson.\r\nServez en avec les œufs durs coupés en deux et parsemez d\'amandes grillées.', '', 'tajine_agneau_pruneaux_min.jpg', 'tajine_agneau_pruneaux.jpg', 'tajine d\'agneau aux pruneaux', 'tajine_agneau_pruneaux_grd.jpg'),
	(17, '2018-09-09 05:37:47', '1', 'Crevettes aux raisins.', 'Crevettes, raisins, france', '2', 2, 'Toujours dans la simplicité et le raffinement.', 4, 'facile', 'Des crevettes crues\r\nDes raisins blancs', 'Poivre', '00:20:00', '00:10:00', 'Faire bouillir de l\'eau dans une casserole.\r\nPréparer un saladier avec de l\'eau et des glaçons.\r\nTremper les raisins dans l\'eau bouillante environ 15 secondes.\r\nLes mettre ensuite dans l\'eau glacée.\r\nPuis les éplucher.\r\nDécortiquez les crevettes crues.', 'Faites revenir les grains de raisins dans une poêle,\r\najouter les crevettes et les faire sauter pour qu\'elles caramélisent légèrement.\r\n', 'Ne pas trop faire cuire les crevettes sinon elles deviennent sèches et caoutchouteuses.', 'crevettes_raisins_min.jpg', 'crevettes_raisins.jpg', 'crevettes_raisins', 'crevettes_raisins_grd.jpg'),
	(18, '2018-09-09 13:54:42', '6', 'Poivrons de Padrón', 'espagne, tapas, poivrons, padron,', '1', 1, 'Nous avons découvert cette tapas en Andalousie. Depuis on raffole de ces poivrons. Il existe aussi une variante Marseillaise.', 2, '', '400grs de Poivrons de Padrón.', 'Huile d\'olive,\r\nfleure de sel,\r\nail.', '00:05:00', '00:10:00', 'Laver et sécher les poivrons.', 'Faire chauffer de l\'huile à  feu moyen,\r\nmettre les poivrons à revenir dedans,\r\nretournez les souvent pour éviter de les brûler.\r\nAjouter l\'ail écrasé.\r\nBaissez le feu et couvrez pendant 5min.\r\nServez et saupoudrez de fleur de sel. ', '', 'poivrons_padron_min.jpg', 'poivrons_padron.jpg', 'Poivrons de Padrón', 'poivrons_padron_grd.jpg'),
	(19, '2018-10-04 13:17:55', '1', 'Bar en papillote', 'poisson, france', '2', 2, 'Le bar est un de nos poissons préféré parcequ\'il n\'a pas besoin de recette sophistiquée pour être délicieux.', 2, 'facile', 'Un beau bar de 500 grs,\nun citron bio.', 'Huile,\r\nThym,\r\nSel,\r\nPoivre.', '00:10:00', '00:20:00', 'Videz et écaillez votre bar,\nsur une feuille de papier sulfurisée posez le bar avec,\ndes rondelles de citrons et des brins de thym, dessous, dedans et dessus,\narrosez d\'un mince filet d\'huile d\'olive,\nfermez la papillote comme un gros bonbon.', 'Préchauffez le four à 200 degrés,\r\nposer la papillote dans un plat qui va au four.\r\nEnfournez et laisser cuire 20 minutes.', 'Adaptez le temps de cuisson en fonction de la taille de vôtre poisson, afin de ne pas avoir un poisson sec sur la table. Sur la photo on voit des tranches de piments Japaleno, inutile d\'essayer. C\'est une initiative malheureuse, çà n\'apporte pas grand chose au goût.', 'bar_papillote_min_02.jpg', 'bar_papillote_02.jpg', 'bar_papillote_02', 'bar_papillote_grd_02.jpg'),
	(20, '2018-10-08 05:41:37', '2', 'Salade de tomates aux pignons.', 'tomates, salade, pignons, France, méditerranée ', '2', 2, 'Une délicieuse salade méditerranéenne avec un accent indien.', 4, 'facile', '4 tomates, \n1 oignon, \npignons, \ncoriandre fraîche, \npiment vert frais.', 'Garam masala,\r\nhuile d\'olive.', '00:15:00', '00:00:00', 'Coupez les tomates et l\'oignon en petits dés dans un saladier.\r\nParsemez avec la coriandre hachée et les pignons grillés.\r\nAjoutez un filet d\'huile d\'olive.\r\nSaupoudrez le tout de garam masala.', 'Sans.', 'Le piment vert est facultatif.\r\nPensez à retirer les graines s\'ils sont très piquants.', 'salade_tomates_pignons_min_01.jpg', 'salade_tomates_pignons_01.jpg', 'Salade de tomates aux pignons.', 'salade_tomates_pignons_grd_01.jpg'),
	(21, '2018-10-08 07:29:24', '4', 'Tajine d\'agneau aux courgettes', 'courgettes, agneau, tajine, tagine, Maroc', '4', 4, 'Un petit tajine pour apprécier les premières courgettes de la saison.', 4, 'facile', '1 épaule d\'agneau,\n2 belles courgettes,\n1 gros oignon,\n2 piments verts frais,\ndes olives dénoyautées,\n1/2 citron confit.', 'Curcuma,\nras el hanout,\ncoriandre moulue,\ngingembre moulu,\ncumin,\nhuile d\'olive,\nsel,\npoivre.', '00:25:00', '01:00:00', 'Dégraissez l\'épaule d\'agneau et coupez la en morceaux.\nÉmincez l\'oignon.\nCoupez les courgettes en morceaux moyens.\nRetirez la pulpe du citron et coupez le en lanières.\nRincez les olives.\nHachez la coriandre fraîche.', 'Faites revenir les morceaux d\'épaule sur toute leurs faces. Réservez.\nFaites fondre l\'oignon dans un peu d\'huile d\'olive.\nRemettez la viande dans la marmite.\nAjoutez toutes les épices.\nCouvrez à hauteur d\'eau.\nFaire mijoter 1 heure.\n20 minutes avant la fin rajouter le citron confit, les piments vert entiers et les olives.\nServez avec de la coriandre fraîche hachée.\nVeillez à avoir assez de sauce, rajoutez de l\'eau au besoin.', 'Attention à ne pas percer le piment pendant la cuisson. Vous pouvez accompagner ce plat d\'un bon riz basmati ou bien d\'un bon pain.', 'tajine_agneau_courgette_min.jpg', 'tajine_agneau_courgette.jpg', 'tajine agneau courgette', 'tajine_agneau_courgette_grd.jpg'),
	(22, '2019-05-06 08:07:54', '7', 'Chutney de coriandre', 'coriandre, chutney, Indes', '3', 3, 'Pour accompagner un plat indien.', 4, 'facile', '1 bouquet de coriandre fraîche\r\n1 gousse d’ail\r\n1 c.à.s de gingembre frais émincé\r\n1 piment vert frais\r\n1 c.à.s de crème de noix de cajou\r\n2 c.à.s de jus de citron\r\n', 'sel', '00:10:00', '00:00:00', 'Lavez et hachez la coriandre grossièrement.\r\nÉmincez l\'ail et le gingembre.\r\nEnlevez les graines du piment et hachez-le.\r\nMixez tous les ingrédients avec un peu d\'eau.\r\nConsommez de préférence dans la journée.', 'Pas de cuisson', 'Vous pouvez utiliser des cacahuètes à la place des noix de cajou ou bien des pignons grillés.', 'chutney_coriandre_min.jpg', 'chutney_coriandre.jpg', 'Chutney de coriandre', 'chutney_coriandre_grd.jpg'),
	(23, '2019-07-05 09:04:44', '0', 'Frites géantes', 'féculents, patates, pommes de terres, France, frites,', '2', 2, 'Pour une envie de frites sans qu\'elles soient trop grasses.', 2, 'facile', '2 belles pommes de terre à frites.', 'huile\r\nsel', '00:10:00', '00:30:00', 'Épluchez les Pdt.\r\nEn fonction de la taille des Pdt coupez une ou deux frites puis lavez les.', 'Faites précuire les frites à la vapeur. Elles doivent être encore un peu ferme.\r\nEnsuite séchez les au papier absorbant.\r\nVersez un peu d\'huile dans une poêle et terminez la cuisson des frites en les faisant frire sur chaque face.\r\nQuand elles sont bien dorées les poser sur papier absorbant et servir.', '', 'frites_géantes_01_min.JPG', 'frites_géantes_01.JPG', 'Frites géantes', 'frites_géantes_01_grd.JPG'),
	(24, '2019-07-05 09:38:45', '5', 'Lasagne de melon aux fraises', 'melon, melon jaune, fraises, menthe, France', '2', 2, 'Un délice d\'été.', 2, 'facile', '1 melon jaune\r\ndes fraises\r\nde la menthe fraîche\r\nde l\'eau de fleur d\'oranger.', '', '00:15:00', '00:00:00', 'Passez les fruits à la mandoline environ 4 millimètre.\r\nArrosez les d\'un peu d\'eau de fleur d\'oranger.\r\nDans un moule sans fond placez une couche de melon puis une de fraise et ainsi de suite jusqu\'à une hauteur de 5 à 6 cm.\r\nFinissez par une couche de melon.\r\ndécorez avec une feuille de menthe et une fraise.', '', '', 'lasagne_melon_fraise_min', 'lasagne_melon_fraise', 'Lasagne de melon aux fraises', 'lasagne_melon_fraise_grd'),
	(25, '2019-10-17 15:17:49', '4', 'Tajine aux coings.', 'tajine, agneau, coing, Maroc', '4', 4, 'Le coing on le connaît surtout en compote, confiture, gelée ou pâte de fruit.\r\nMais en tajine sucré/salé avec de l\'agneau et du safran c\'est un pur délice.', 4, 'facile', '1 kg d\'agneau,\r\n1/2 kg de coings,\r\n2 oignons,\r\n1/2 citron,\r\n4 gousses d\'ail.\r\n', '1/2 c.à.c de gingembre en poudre,\r\n1/2 dose de colorant safran,\r\nQuelques pistils de safran,\r\n2 c.à.s de sucre en poudre,\r\n1/2 c.à.c de cannelle ou un bâton.', '00:30:00', '01:00:00', 'Dégraisser l\'agneau si besoin et couper en morceaux.\r\nHachez les oignons.\r\nLavez et brossez les coings.\r\nCoupez les coings en 4 ou 8 quartiers, en fonction de leur taille, enlevez généreusement le cœur avec les pépins.\r\nLes mettre tout de suite dans récipient contenant de l\'eau et le jus d\'un demi citron pour éviter qu\'ils ne noircissent.\r\n', 'Saisir la viande dans de l\'huile et réservez.\r\nFaites fondre les oignons.\r\nRemettez la viande, ajoutez les épices et remplissez à hauteur d\'eau.\r\nFaire cuire environ 45 min.\r\nPendant ce temps, pocher les coings puis égoutter.\r\nEnsuite rajouter le sucre et la cannelle de l\'eau et confire tout çà en remuant de temps en temps.\r\n', '', 'tajine_aux_coings_min.jpg', 'tajine_aux_coings.jpg', 'Tajine aux coings.', 'tajine_aux_coings_grd.jpg'),
	(26, '2019-10-21 16:22:47', '4', 'Tajine d\'agneau à la patate douce.', 'tajine, agneau, patate douce, maroc', '4', 4, 'Spécialité marocaine sucrée salée qui vous enchantera par sa douceur.', 4, 'facile', '1 demie épaule d\'agneau désossée,\r\n1 patate douce,\r\n9 abricots secs,\r\n1 oignon,\r\n2 gousses d\'ail,\r\n3 c.à.s de coriandre ciselée.', '3/4 c.à.c. de curcuma,\r\n1/2 c.à.c. de gingembre moulu,\r\n1/2 c.à.c. de cumin en poudre,\r\n1 c.à.s. d\'huile d\'olive,\r\n1/2 bouillon cube de mouton,\r\npoivre.', '00:30:00', '00:45:00', 'Émincer l\'oignon et faire fondre dans un peu d\'huile d\'olive, mettre l\'ail écrasé, rajouter les épices,\r\ncouper la viande en morceaux de taille moyenne,\r\nles mettre à revenir 2 3 minutes avec les oignons, couvrir à hauteur d\'eau et mettre le bouillon cube.\r\n\r\n', 'Portez à ébullition et faire mijoter couvert à feu moyen pendant 45 min à 1 heure.\r\nRéservez la viande quand elle est cuite. Mettre la patate douce pelée et coupée en morceaux ainsi que les abricots préalablement trempés dans de l\'eau chaude.', '', 'tajine_agneau_patates_douce_min.JPG', 'tajine_agneau_patates_douce.JPG', 'tajine d\'agneau à la patate douce.', 'tajine_agneau_patates_douce_grd.JPG'),
	(27, '2019-10-31 10:00:47', '0', 'Soupe de légumes et merguez.', 'merguez, pois chiches, légumes, méditerranée, soupe', '12', 12, 'Plat unique original.', 4, 'facile', '4 Merguez\r\n2 Pommes de terres\r\n2 Tiges de vert de poireaux\r\n1 Poignée d\'épinard\r\n1 Branche de céleri\r\n1 Oignon émincé\r\n3 Gousses d\'ail émincées\r\n400 grs de pois chiches\r\n1 Boite de tomates concassées\r\n1 c.à.s. de concentré de tomate\r\n1 Bouquet garni\r\n1 Bouillon de légumes', '1 c.à.c. de mélange 4 épices\r\nSel\r\nPoivre\r\n1 c.à.s. d\'huile d\'olive', '00:15:00', '00:35:00', 'Épluchez et émincez l\'oignon et l\'ail,\r\nHachez les tiges de poireaux et la branche de céleri. \r\nPréparez le bouillon.\r\nÉpluchez et coupez en petits cubes les pommes de terre.', 'Faire fondre l\'oignon, l\'ail, les tiges de vert de poireaux et la branche de céleri pendant 5mn tout en remuant.\r\nVersez le bouillon de légumes, les tomates concassées, les pois chiches, le concentré de tomate, le bouquet garni.\r\nFaire bouillir 10mn.\r\nAjouter les pommes de terres.\r\nMettre aussi les merguez coupées en morceaux.\r\nContinuer la cuisson environ 20mn.', 'Si vous êtes patient vous pouvez enlever la peau des pois chiches. C\'est un peu long mais c\'est juste un coup de main à prendre.', 'soupe_avec_mergez_min.png', 'soupe_avec_mergez.png', 'Soupe de légumes et merguez.', 'soupe_avec_mergez_grd.jpg'),
	(28, '2019-11-14 15:53:13', '0', 'Lentilles à la marocaine', 'légumineuses, lentilles, maroc', '4', 4, 'Un super plat économique, qui vous fera aimer les lentilles.', 4, 'facile', '250 grs de lentilles blondes\r\n1 oignon moyen\r\n1 tomate\r\n4 gousses d\'ail écrasées\r\n1 càs de concentré de tomate\r\ndu persil\r\nde la coriandre\r\n1 piment vert (facultatif)', 'de l\'huile d\'olive\r\ndu sel\r\ndu poivre\r\ndu safran colorant\r\ndu cumin en poudre\r\ndu piment en poudre\r\n\r\n', '00:10:00', '00:35:00', 'Laver les lentilles.\r\nÉmincer l\'oignon.\r\nPeler et écraser les gousses d\'ail.\r\nCouper la tomate en morceaux. C\'est mieux si elle est pelée avant.\r\n', 'Mettre les lentilles dans une marmite,\r\najouter l\'oignon, l\'ail, la tomate, le concentré de tomate, l\'huile, le poivre, le safran colorant, le cumin en poudre et 2 verres d\'eau.\r\nMettez le tout à mijoter environ 35 minutes. Salez seulement à la fin de la cuisson.\r\nServez chaud avec du persil et de la coriandre hachée.', 'Si vous aimez épicé vous rajouterez le piment en poudre ou vous mettrez le piment vert à cuire avec en faisant attention à ne pas l\'éclater pendant la cuisson.\r\nSi votre eau est très calcaire mettez un peu de bicarbonate pour que les lentilles ne soient pas dures.', 'lentilles_a_la_marocaine_min.jpg', 'lentilles_a_la_marocaine.jpg', 'Lentilles à la marocaine', 'lentilles_a_la_marocaine_grd.jpg'),
	(29, '2020-03-30 15:51:12', '8', 'Raïta de concombre (Express)', 'raïta, concombre', '3', 3, 'Pour accompagner beaucoup de plats indiens et adoucir le feu du piment.', 2, 'facile', '2 yaourts\r\n1 concombre\r\n1 gousse d\'ail\r\n1 1/2 bouquet de menthe', 'sel\r\npoivre\r\npiment en poudre', '00:15:00', '00:00:00', 'Eplucher le concombre et enlever les graines .\r\nLe passer au mixer plongeant pour faire comme s\'il avait été râpé.\r\nPuis le mettre à égoutter dans une passoire (on gagne 1 heure d\'attente).\r\nPeler et enlever le coeur de la gousse d\'ail et la piler en purée.\r\nHacher très finement la menthe.\r\nBien secouer les yaourts dans leurs pots avant de les ouvrir (toujours pour gagner du temps).\r\nMélanger le tout dans un saladier avec les épices et réservez au frais.', '', 'Pour enlever le coeur du concombre prenez une petite cuillère, c\'est beaucoup plus facile.', 'raita de_concombre_min.jpg', 'raita de_concombre.jpg', 'Raïta de concombre', 'raita de_concombre_grd.jpg'),
	(30, '2020-04-03 10:25:45', '5', 'Gâteau au chocolat à l\'eau', 'gâteau, chocolat, à l\'eau,', '2', 2, 'Un gâteau diététique sans lait ni oeufs et très peu de matière grasse.', 8, 'facile', '1/3 de litre d\'eau\r\n250 grs de farine\r\n200 grs de chocolat\r\n100 grs de sucre\r\n5 cl d\'huile\r\n1 sachet de levure chimique\r\n1 gousse de vanille\r\n', '', '00:20:00', '00:45:00', 'Faire fondre le chocolat sans le brûler.\r\nFaire fondre le sucre dans l\'eau chauffée.\r\nAjouter l\'eau sucrée petit à petit au chocolat (pour éviter les grumeaux).\r\nAjouter l\'huile.\r\nAjouter la pulpe de la vanille.\r\nMélanger la levure à la farine.\r\nVerser la farine dans une passoire fine.\r\nTamisez la farine au dessus du chocolat dilué tout en battant la préparation à l\'aide d\'un fouet. Normalement il n\'y a pas de grumeaux.\r\nVersez le tout dans un moule huilé. ', 'Préchauffez le four à 180°. (chaleur tournante).\r\nEnfournez pour une durée de 45 min.\r\nVérifiez à terme avec un cure dent.\r\nS\'il ressort sec, c\'est que c\'est cuit.', '', 'gateau_au_chocolat_et_eau_min.jpg', 'gateau_au_chocolat_et_eau.jpg', 'Gâteau au chocolat à l\'eau', 'gateau_au_chocolat_et_eau_grd.jpg'),
	(31, '2020-04-05 14:52:41', '4', 'Tajine au carottes et pommes de terre.', 'tajine, carottes, pommes de terre, pdt, olives,', '4', 4, 'Un excellent tajine pour changer du fameux tajine aux pruneaux.', 6, 'facile', '1 épaule d\'agneau désossé\r\n1 gros oignon\r\n3 gousses d\'ail\r\n5 carottes\r\n6 pommes de terre\r\ndes olives vertes\r\n1/2 citron confit sans la pulpe\r\n1/2 bouquet de coriandre', 'Coriandre en poudre\r\nGingembre en poudre\r\nCurcuma en poudre\r\nCumin en poudre\r\nPiment en poudre\r\nSel\r\nPoivre\r\n1 bouillon d\'agneau\r\n2 càs d\'huile', '00:30:00', '02:00:00', 'Dégraissez l\'épaule d\'agneau et détaillez la en gros morceaux.\r\nPelez et émincez l\'oignon et l\'ail.\r\nPelez les carottes et les pommes de terre, coupez les en trois puis en quatre sur la longueur.\r\nCoupez le citron confit en lanières\r\nLavez et ciselez la coriandre', 'Faire saisir les morceaux de viande dans une sauteuse avec un peu d\'huile puis réservez.\r\nFaites fondre les oignons et l\'ail jusqu\'à la limite de la coloration. Ajoutez un peu d\'huile au besoin.\r\nRemettez la viande dans la sauteuse.\r\nRajoutez les épices, le bouillon d\'agneau et couvrez à hauteur d\'eau.\r\nFaites mijoter à feu doux pendant 1 heure.\r\nMettez les carottes et les lanières de citron confit.\r\n20 minutes après rajoutez les pommes de terre pendant 20 minutes.\r\nMettez les olives 10 mn avant la fin.\r\nServez et saupoudrez de coriandre ciselée.', '', 'tajine_agneau_carottes_min.jpg', 'tajine_agneau_carottes.jpg', 'Tajine au carottes et pommes de terres', 'tajine_agneau_carottes_grd.jpg'),
	(32, '2020-04-08 14:53:15', '3', 'Haricots blancs secs (Loubia)', 'haricots, loubia,', '4', 4, 'Un classique de la cuisine marocaine.', 4, 'facile', '250 grs de haricots blancs secs\r\n2 tomates\r\n4 gousses d\'ail\r\nPersil\r\nCoriandre\r\nEau', 'Safran colorant\r\nCumin\r\nConcentré de tomate\r\nHuile\r\nSel\r\nPoivre', '00:20:00', '00:00:00', 'La veille faites tremper les haricots dans une grande quantité d\'eau.\r\nLe jour de la cuisson faites les pocher dans de l\'eau environ 20 min.\r\nPendant ce temps coupez les tomates en dés.\r\nPelez et écrasez l\'ail.\r\nLavez et hachez le persil et la coriandre.\r\n', 'Mettez le tout dans une marmite avec les épices et de l\'eau.\r\nFaire mijoter jusqu\'à que les haricots soient fondants.', 'Pour les épices il n\'y a pas d\'indication de quantité il faudra vous faire votre propre dosage en fonction de vos goûts.\r\nSi votre eau est très calcaire pensez au bicarbonate de soude.\r\n', 'haricots_blancs_secs_min.jpg', 'haricots_blancs_secs.jpg', 'Haricots blancs secs (Loubia)', 'haricots_blancs_secs_grd.jpg'),
	(33, '2020-04-10 07:38:42', '3', 'Aubergines frites', 'aubergine, maroc,', '4', 4, 'Un peu de méditerrannée dans notre assiette.', 4, 'facile', '2 grosses aubergines\r\nFarine\r\nHuile', 'sel\r\npoivre', '00:40:00', '00:30:00', 'Coupez les aubergines en rondelles.\r\nPlacez les dans une passoire en les saupoudrant généreusement entre chaque couche pour les faire dégorger pendant 30 min.\r\nPuis rincez les à l\'eau froide et faites le sécher.\r\nMettez de la farine dans un sac plastique.', 'Faire chauffer l\'huile dans une grande poêle.\r\nMettez un nombre suffisant de rondelles pour remplir votre poêle dans le sac avec la farine.\r\nSecouez bien pour que toutes les rondelles soient farinées.\r\nMettez à cuire dans la poêle 2 ou 3 minutes de chaque côté.\r\nUne fois qu\'elles sont bien dorées les déposer sur du papier absorbant.\r\nEt ainsi de suite.', 'Vous pouvez améliorer votre farine en y incorporant des épices ou des herbes selon vos goûts et imagination.\r\nAttention mettez le moins d\'huile possible, car l\'aubergine l\'absorbe comme une éponge.', 'aubergines_frites_min.jpg', 'aubergines_frites.jpg', 'Aubergines frites', 'aubergines_frites_grd.jpg'),
	(34, '2020-04-11 10:38:04', '6', 'Tapas d\'artichauts', 'espagne, tapas, artichaut, artichauts,', '1', 1, 'Un air d\'Espagne pour changer des tapas traditionnelles.', 4, 'facile', '1 bocal de coeurs d\'artichauts\r\n1 gousse d\'ail\r\nHuile d\'olive\r\nHerbes fraîches au choix', 'Sel', '00:10:00', '00:00:00', 'Coupez les artichauts en deux ou quatre selon leur grosseur.\r\nPelez et hacher l\'ail très finement.\r\nMélanger le tout avec de l\'huile d\'olive.\r\nFaites marinez 1/2 heures.\r\nParsemez d\'herbes choisies.\r\nSalez si besoin.', 'Sans', '', 'tapas_artichauts_min.jpg', 'tapas_artichauts.jpg', 'Tapas d\'artichauts', 'tapas_artichauts_grd.jpg'),
	(35, '2020-04-11 13:49:16', '2', 'Salade tomates poivrons', 'Maroc, tomates, poivrons, ail', '4', 4, 'Pour accompagner un tajine de viande.', 4, 'facile', '2 grosses tomates\r\n2 gros poivrons\r\n1 gousse d\'ail\r\nJus d\'un demi citron\r\nCoriandre fraîche', 'Cumin\r\nHuile\r\nSel\r\nPoivre\r\n', '00:00:00', '00:00:00', 'Faites griller les poivrons et puis mettez les dans une boite en plastique qui se ferme hermétiquement.\r\nComme çà vous pourrez enlever la peau plus facilement.\r\nFaites bouillir de l\'eau et trempez y les tomates jusqu\'à ce que la peau éclate.\r\nTrempez les de suite dans de l\'eau glacée pour arrêter la cuisson.\r\nCoupez les en deux pour retirer les graines et le jus.\r\nDétaillez les poivrons et les tomates en lanière ou morceaux.\r\nHachez finement l\'ail.\r\nPressez le demi citron.\r\nLavez et hachez la coriandre.\r\nMélangez le tout avec les condiments et c\'est prêt.', '', '', 'salade_tomates_poivrons_min.jpg', 'salade_tomates_poivrons.jpg', 'Salade tomates poivrons', 'salade_tomates_poivrons_grd.jpg'),
	(36, '2020-04-12 14:22:19', '1', 'Congre à la sauce au safran', 'congre, safran, poisson', '2', 2, 'Le retour de ce mal aimé, le congre.', 4, 'facile', '4 darnes de congre\r\n2 gros oignons\r\n20 cl de crème semi liquide\r\n', '1 cube de court bouillon\r\nSafran\r\nSel\r\nPoivre', '00:15:00', '00:15:00', '1 heure avant de commencer faites tremper les pistils de safran dans de l\'eau chaude.\r\nLavez vos darnes de congre.\r\nPréparez votre court bouillon.\r\nHachez les oignons', 'Commencez par faire fondre les oignons avec un peu d\'huile jusqu\'à la limite de la coloration.\r\nMettez les darnes de congre dans le court bouillon pour 10 min.\r\nQuand les oignons sont prêt vous mettez le safran avec son eau pour déglacer et faites un peu évaporer l\'eau.\r\nRéduisez le feu ajoutez la crème (ne la faites pas bouillir).\r\nMettez les darnes dans cette préparation 2 ou 3 min par face.\r\nServez du riz ou des pommes de terre vapeur.', 'Arrivez tôt chez votre poissonnier pour pour avoir des morceaux de congre le plus près de la tête, c\'est ceux qui ont le moins d\'arête.', 'congre_sauce_safran_min.jpg', 'congre_sauce_safran.jpg', 'Congre à la sauce au safran', 'congre_sauce_safran_grd.jpg'),
	(37, '2020-04-13 10:10:40', '1', 'Sardines crues au citron', 'sardine, cru, crues, citron, graines de coriandre', '2', 2, 'Une petite entrée bien estivale.', 4, 'facile', '16 sardines (méditerranéennes de préférence)\r\n1 citron\r\nHuile d\'olive', 'Graines de coriandre\r\nSel', '00:15:00', '01:00:00', 'Videz, lavez, enlevez la tête et l\'arête centrale.\r\nPlacez les filets sur le dos dans un plat.\r\nPressez le citron.\r\nPilez les graines de coriandre.\r\nMélangez le tout et versez sur les sardines.\r\nLaisser mariner environ 1 heure.\r\nServez saupoudré de fleur de sel.', 'Sans', 'Parsemez de basilic ou de coriandre.', 'sardines_crues_citron_min.jpg', 'sardines_crues_citron.jpg', 'Sardines crues au citron', 'sardines_crues_citron_grd.jpg'),
	(38, '2020-04-14 08:58:51', '5', 'Gâteau au chocolat', 'gâteau, chocolat, dessert, France, beurre, œufs', '2', 2, 'Un bon gâteau au chocolat.', 8, 'facile', '90 gr de farine\r\n200 gr de chocolat\r\n70 gr de beurre\r\n80 gr de sucre\r\n4 œufs\r\n1 càs d\'eau de fleur d\'oranger', '', '00:20:00', '00:50:00', 'Faites fondre le chocolat au bain marie avec le beurre.\r\nAjoutez les jaunes d’œufs l\'un après l\'autre.\r\nPuis la farine et le sucre.\r\nMontez les blancs en neige avec l\'eau de fleur d\'oranger.\r\nIncorporez délicatement les blancs en neige à la préparation.\r\nPuis versez la dans un moule beurré.\r\nMettez à cuire 50 min dans un four préchauffé à 140°.', '', '', 'gateau_au_chocolat_beurre_oeufs_min.jpg', 'gateau_au_chocolat_beurre_oeufs.jpg', 'Gâteau au chocolat', 'gateau_au_chocolat_beurre_oeufs_grd.jpg'),
	(39, '2020-04-19 10:38:40', '0', 'Pizza épaisse', 'pizza, épaisse, Italie,', '6', 6, 'Rien ne vaut une pizza faite avec une pâte maison.', 2, 'facile', '300 grs de farine\r\n1 sachet de levure\r\n1 càs d\'huile\r\nSel', '', '01:15:00', '00:19:00', 'Préparez la pâte à pizza, en versant la farine, la levure, l\'huile et le sel dans un saladier.\r\nFaites tiédir un peu d\'eau.\r\nVersez de l\'eau tiède au fur et à mesure jusqu\'à obtention d\'une pâte souple qui d\'attache pas.\r\nTravaillez la pâte jusqu\'à ce qu\'elle devienne lisse et élastique.\r\nHuilez un saladier mettre la pâte dedans, filmez et laisser lever 1 h environ.\r\nMais plus vous la laisserez lever mieux c\'est (une histoire de maturation des arômes).', 'Préchauffez votre four sur fonction pizza.\r\nPlacez un bol d\'eau chaude en bas, pour avoir de la vapeur.\r\nÉtalez votre pâte à la main du centre vers les bords.\r\nGarnissez votre pizza selon vos envies et enfournez.\r\nLa fonction pizza fait cuire environ 19 min. Si se n\'est pas assez laissez la plus longtemps.', 'Ne mettez pas la levure et le sel du même côté.\r\n', 'pizza_epaisse_min.jpg', 'pizza_epaisse.jpg', 'Pizza épaisse', 'pizza_epaisse_grd.jpg'),
	(40, '2020-04-23 15:05:26', '3', 'Houmous de carottes', 'houmous, carottes, oranges, gingembre, coriandre, frais, végétarien,', '2', 2, 'Frais et léger pour changer de la sempiternelle salade de carottes.', 2, 'facile', '4 carottes\r\n1 orange\r\n1 morceaux de gingembre\r\nCoriandre fraîche', 'Sel\r\nPoivre', '00:15:00', '00:00:00', 'Pelez et détaillez les carottes en petits morceaux.\r\nPressez le jus de l\'orange.\r\nMixez les carottes avec le jus d\'orange.\r\nPelez et hachez menu le gingembre et incorporez le à la mixture.\r\nSalez et poivrez, mélangez le tout et si c\'est trop sec rajoutez de l\'eau ou du jus d\'orange.\r\nParsemez de coriandre fraîche.\r\nVous pouvez le manger à l\'apéro ou en accompagnement.', 'Sans.', 'Vous pouvez rajouter une càs de miel.\r\nRégalez vous.', 'houmous_de_carottes_min.jpg', 'houmous_de_carottes.jpg', 'houmous_de_carottes.jpg', 'houmous_de_carottes_grd.jpg'),
	(41, '2020-04-23 16:00:38', '1', 'Bar au four à l\'asiatique', 'poisson, bar, four, gingembre, sauce soja, asie, asiatique,', '5', 5, 'Une merveille si le bar n\'est pas trop cuit.', 2, 'facile', '1 bar moyen vidé et écaillé\r\n1 morceaux de gingembre frais\r\n1 gousse d\'ail\r\n3 càs de sauce soja\r\n2 càs de vin de riz\r\n2 càs d\'eau\r\n1 càf de pâte de piment (facultatif)', '1 càs de sucre\r\nPoivre', '00:15:00', '00:20:00', 'Lavez le bar.\r\nMettez dans un bol la sauce soja, le vin de riz, le sucre et l\'eau.\r\nRajoutez l\'ail et 1/3 du morceau de gingembre hachés menu.\r\nMettez la sauce dans un plat allant au four, posez le poisson.\r\nCoupez le reste du gingembre en filaments et parsemez le plat et le bar avec.\r\n', 'Préchauffez le four à 180°.\r\nRecouvrez le plat d\'aluminium ou de papier cuisson.\r\nFaites cuire environ 20 min selon la taille du poisson.\r\nIl est impératif que le bar ne soit pas sec au sortir du four.', 'Vous pouvez le servir avec du riz de votre choix mais la recette s\'accommode bien avec légumes vapeur ou sautés.', 'bar_au_four_asiatique_min.jpg', 'bar_au_four_asiatique.jpg', 'bar_au_four_asiatique_grd.jpg', 'bar_au_four_asiatique_grd.jpg'),
	(42, '2020-04-26 07:12:31', '0', 'Soupe de fanes de radis', 'soupe, fanes, radis, France, ', '2', 2, 'Une petite soupe de printemps.', 2, 'facile', '1 belle botte de radis\r\n1 pomme de terre moyenne\r\n1 oignon', '½ bouillon au choix\r\nHuile\r\nPoivre', '00:15:00', '00:20:00', 'Pelez et émincez l\'oignon.\r\nCoupez les fanes des radis dans un saladier.\r\nEnlevez les feuilles jaunes ou pourries et les adventices (mauvaise herbes) qui se seraient immiscées dans la botte.\r\nRincez et égouttez les fanes.\r\nPelez et coupez la pommes de terre en petits dés.\r\nFaites fondre le bouillon dans un peu d\'eau chaude.\r\n', 'Faites fondre l\'oignon dans un filet d\'huile.\r\nMettez les fanes des radis à fondre avec les oignons.\r\nAjoutez la pommes de terre.\r\nMettez le bouillon, le poivre et rajoutez de l\'eau à hauteur.\r\nLaissez mijoter environ 20 min.\r\nComme il y a du bouillon il est inutile de saler.\r\nMixez la soupe et servez chaud.', 'Vous pouvez remplacer l\'huile par du beurre.\r\nRajouter un trait de crème fraîche dans l\'assiette avant de servir.\r\nSi vous voulez une soupe un peu plus veloutée rajoutez une pomme de terre.\r\nPlus vous couperez les pommes de terre en petits dés moins la cuisson sera longue.', 'soupe_fanes_de_radis_min.jpg', 'soupe_fanes_de_radis.jpg', 'soupe_fanes_de_radis_grd.jpg', 'soupe_fanes_de_radis_grd.jpg'),
	(43, '2020-04-27 15:11:25', '6', 'Tapas de sardines en boite', 'tapas, sardines, sauce soja, citron, échalottes, menthe,', '2', 2, 'Pour déguster les sardines en boite autrement.', 2, 'facile', '1 boite de sardines au choix\r\n1 échalote\r\n1 morceau de gingembre frais\r\n1 càs de jus de citron au choix\r\n1 càs de sauce soja\r\n2 càs d\'eau\r\n3 grosse feuille de menthe', '', '00:10:00', '00:00:00', 'Pelez et émincez finement l\'échalote.\r\nCoupez le gingembre en julienne.\r\nCiselez les feuilles de menthe.\r\nExprimez le jus du citron dans une assiette rajoutez la sauce soja, l\'eau et le reste des ingrédients.\r\nMélangez et laissez mariner 5 min.\r\n', 'Sans', 'Vous pouvez choisir d\'autres herbes que la menthe en fonction de la saison.', 'tapas_sardines_boite_min.jpg', 'tapas_sardines_boite.jpg', 'tapas_sardines_boite.jpg', 'tapas_sardines_boite_grd.jpg'),
	(44, '2020-05-01 10:08:02', '0', 'Pissaladière', 'pissaladière, oignons, Nice, Provence, Côte d\'Azur, olives,', '2', 2, 'Une pissaladière c\'est sur de la pâte à pain. Sinon faites autre chose.', 4, 'facile', 'Pour la pâte :\r\n250 grs de farine\r\n1 sachet de levure\r\n1 càs d\'huile d\'olive\r\nSel\r\nPour la garniture :\r\n500 grs d\'oignons\r\nAnchois à l\'huile\r\nOlives noires\r\nHuile d\'olive\r\n1 càs de sucre\r\nThym\r\nOrigan\r\nPoivre', '', '01:00:00', '00:30:00', 'Préparez la pâte à pizza, en versant la farine, la levure, l\'huile et le sel dans un saladier.\r\nFaites tiédir un peu d\'eau.\r\nVersez de l\'eau tiède au fur et à mesure jusqu\'à obtention d\'une pâte souple qui d\'attache pas.\r\nHuilez un saladier mettre la pâte dedans, filmez et laisser lever 1 h environ.\r\nPour la garniture : \r\nPendant que la pâte lève, pelez et émincez les oignons.', 'Versez un peu d\'huile d\'olive dans une sauteuse et mettez les oignons à fondre sans les faire brunir.\r\nAjoutez 3 ou 4 anchois et faites les fondre avec les oignons.\r\nAjoutez le sucre, le poivre et laisser mijoter à feu doux 15 à 20 min.\r\nÉtalez la pâte pour qu\'elle soit assez épaisse.\r\nGarnissez la avec la préparation décorez avec des anchois entiers et des olives.\r\nEnfournez 25 ou 30 min à 180°. Tout en vérifiant l\'avancement de la cuisson.\r\nAvant de servir parsemez de thym et d\'origan.\r\nDégustez tiède ou froid, en apéritif ou avec une salade', '', 'pissaladiere_min.jpg', 'pissaladiere.jpg', 'pissaladiere.jpg', 'pissaladiere_grd.jpg'),
	(45, '2020-05-02 10:36:58', '0', 'Boulettes de pain rassis au thon', 'boulettes, pain rassis, thon, vert d\'oignon, tapas,', '2', 2, 'En tapas ou en entrée une recette facile à faire.', 2, 'facile', '125 gr de pain rassis\r\n1 boîte de thon\r\n1 œuf\r\n1 oignon frais', 'Cumin\r\nPaprika\r\nGingembre\r\nCoriandre\r\nPiment\r\nSel\r\nPoivre', '00:30:00', '00:20:00', 'Coupez le pain en morceaux et faites le tremper dans de l\'eau 10 min.\r\nHachez les tiges vertes de l\'oignon frais.\r\nEssorez le pain à la main.\r\nAjoutez l’œuf, les épices, le thon émietté à la fourchette et le vert d\'oignon.\r\nMélangez le tout puis formez des boulettes moyennes.\r\n', 'Posez le tout sur une plaque et enfournez dans un four préalablement préchauffé à 180°; laissez cuire 20 min environ jusqu\'à ce qu\'elles soient dorées.\r\nServez avec un raïta de menthe ou de coriandre et un chutney.', 'Vous pouvez aussi les frire mais c\'est plus gras.', 'boulettes_pain-rassis_thon_min.jpg', 'boulettes_pain-rassis_thon.jpg', 'boulettes_pain-rassis_thon.jpg', 'boulettes_pain-rassis_thon_grd.jpg'),
	(46, '2020-05-07 10:04:49', '2', 'Salade de mâche avec cœurs d\'artichaut et pamplemousse rose', 'salade, mâche, artichaut, pamplemousse, graines de coriandre, France, méditterrannée, entrée, été,', '2', 2, 'Avec cette salade c\'est l\'été tous les jours.', 2, 'difficile', '1 barquette de mâche\r\n1 pamplemousse rose\r\n4 cœurs d\'artichaut\r\n2 càs de pignons de pin', '1 càf de graines de coriandre\r\nHuile\r\nSel\r\nPoivre', '00:25:00', '00:00:00', 'Lavez la mâche et équeutez la puis répartissez la sur les assiettes.\r\nPelez le pamplemousse à vif et levez les suprêmes au dessus d\'un grand bol pour récupérer le jus.\r\nDisposez les suprêmes de pamplemousse en étoile sur le lit de mâche.\r\nCoupez les cœurs d\'artichaut en petits dés et placez les au centre des assiettes.\r\nPilez les graines de coriandre grossièrement et ajoutez les au jus de pamplemousse avec du sel, du poivre et un filet d\'huile d\'olive.\r\nFaites griller le pignons de pin à sec dans une poêle.', '', 'Choisissez un pamplemousse rose doux.\r\nEntrainez vous à lever suprêmes car c\'est pas le jour ou vous recevez des invités que vous y arriverez.\r\nAttention avec les pignons de pin il faut tout le temps les remuer et ne jamais les quitter des yeux, surtout vers la fin, car on a vite fait de les carboniser.', 'salade_mache_artichaut_pamplemousse_min.jpg', 'salade_mache_artichaut_pamplemousse.jpg', 'salade_mache_artichaut_pamplemousse.jpg', 'salade_mache_artichaut_pamplemousse_grd.jpg'),
	(47, '2020-08-25 14:59:25', '6', 'Tapas de poivrons grillés au vinaigre', 'tapas, poivron, grillés, vinaigre', '1', 1, 'En tapas ou en accompagnement d\'une viande ou d\'un poisson grillé.', 4, 'facile', '1 gros poivron ou deux moyens\r\n2 gousses d\'ail\r\nHuile d\'olive de préférence\r\n', 'Sel\r\nPoivre\r\nVinaigre', '00:05:00', '00:20:00', 'Lavez et coupez le poivron en lanières. Pensez à enlever les graines au préalable.\r\n', 'Mettez les à frire à feu moyen dans quatre bonnes cuillères d\'huile.\r\nVous pouvez déjà mettre l\'ail si vous l\'aimez confit, attention à ne pas le faire brûler il faut remuer sans cesse, sinon vous le rajoutez à la fin mais il faudra laisser mariner un peu.\r\nQuand les poivrons sont cuits mettez les dans un bol avec son huile de cuisson.\r\nSalez poivrez et rajoutez un filet de vinaigre de vin.', 'Peu se manger tiède ou froid.\r\nSe conserve quelque jours au frais.', 'poivrons_grillés_01_min.JPG', 'poivrons_grillés_01.JPG', 'Tapas de poivrons grillés au vinaigre', 'poivrons_grillés_01_grd.JPG');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
